// <auto-generated />
using System;
using APBDcw12.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBDcw12.Migrations
{
    [DbContext(typeof(Apbd12Context))]
    [Migration("20250527204700_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBDcw12.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Email = "jkowalski@gmail.com",
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Pesel = "11111111",
                            Telephone = "1111111"
                        },
                        new
                        {
                            IdClient = 2,
                            Email = "jnowak@gmail.com",
                            FirstName = "Julia",
                            LastName = "Nowak",
                            Pesel = "22222222",
                            Telephone = "222222"
                        });
                });

            modelBuilder.Entity("APBDcw12.Models.ClientTrip", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime");

                    b.HasKey("IdClient", "IdTrip")
                        .HasName("Client_Trip_pk");

                    b.HasIndex("IdTrip");

                    b.ToTable("Client_Trip", (string)null);
                });

            modelBuilder.Entity("APBDcw12.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCountry"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCountry")
                        .HasName("Country_pk");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            Name = "Poland"
                        },
                        new
                        {
                            IdCountry = 2,
                            Name = "Spain"
                        });
                });

            modelBuilder.Entity("APBDcw12.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTrip"));

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdTrip")
                        .HasName("Trip_pk");

                    b.ToTable("Trip", (string)null);

                    b.HasData(
                        new
                        {
                            IdTrip = 1,
                            DateFrom = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "desc",
                            MaxPeople = 20,
                            Name = "wyc1"
                        },
                        new
                        {
                            IdTrip = 2,
                            DateFrom = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2022, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "desc",
                            MaxPeople = 30,
                            Name = "wyc2"
                        });
                });

            modelBuilder.Entity("Country_Trip", b =>
                {
                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<int>("IdTrip")
                        .HasColumnType("int");

                    b.HasKey("IdCountry", "IdTrip")
                        .HasName("Country_Trip_pk");

                    b.HasIndex("IdTrip");

                    b.ToTable("Country_Trip", (string)null);

                    b.HasData(
                        new
                        {
                            IdCountry = 1,
                            IdTrip = 1
                        },
                        new
                        {
                            IdCountry = 2,
                            IdTrip = 2
                        });
                });

            modelBuilder.Entity("APBDcw12.Models.ClientTrip", b =>
                {
                    b.HasOne("APBDcw12.Models.Client", "IdClientNavigation")
                        .WithMany("ClientTrips")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("Table_5_Client");

                    b.HasOne("APBDcw12.Models.Trip", "IdTripNavigation")
                        .WithMany("ClientTrips")
                        .HasForeignKey("IdTrip")
                        .IsRequired()
                        .HasConstraintName("Table_5_Trip");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("Country_Trip", b =>
                {
                    b.HasOne("APBDcw12.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("IdCountry")
                        .IsRequired()
                        .HasConstraintName("Country_Trip_Country");

                    b.HasOne("APBDcw12.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("IdTrip")
                        .IsRequired()
                        .HasConstraintName("Country_Trip_Trip");
                });

            modelBuilder.Entity("APBDcw12.Models.Client", b =>
                {
                    b.Navigation("ClientTrips");
                });

            modelBuilder.Entity("APBDcw12.Models.Trip", b =>
                {
                    b.Navigation("ClientTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
